name: nlp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - pandas
  - scipy=1.10.1
  - matplotlib
  - gensim=4.3.2
  - pip
  - pip:
      - torch
      - wandb
      - wordcloud
      - matplotlib-venn
      - datasets
      - huggingface_hub
      - transformers
      - nltk
      - seaborn
